import os
from http.server import SimpleHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse, unquote
import urllib
from http import HTTPStatus

DOCS_SITE = os.path.abspath('.lake/build/doc')

class CustomHTTPRequestHandler(SimpleHTTPRequestHandler):
    # Avoid spurious error messages from /favicon.ico
    def do_GET(self):
        if self.path == '/favicon.ico':
            self.send_response(204)
            self.end_headers()
            return
        elif self.path == '/':
            self.send_response(301)
            self.send_header('Location', '/pde/')
            self.end_headers()
            return

        super().do_GET()


    def translate_path(self, path):
        # Prevent query strings from being treated as file paths
        parsed = urlparse(path)
        path = parsed.path
        path = unquote(path)

        # Serve /pde/* from DOCS_SITE
        if path.startswith('/pde'):
            # HACK: double-slashes are being generated by JS
            path = path.replace('//', '/')
            rel_path = path[len('/pde/'):]
            return os.path.join(DOCS_SITE, rel_path)
        else:
            raise FileNotFoundError(f"File not found: {path}")


if __name__ == '__main__':
    import argparse
    import contextlib

    parser = argparse.ArgumentParser()
    parser.add_argument('port', default=8000, type=int, nargs='?',
                        help='bind to this port '
                             '(default: %(default)s)')
    args = parser.parse_args()

    PORT = args.port
    handler = CustomHTTPRequestHandler
    with HTTPServer(("", PORT), handler) as httpd:
        print(f"Serving at http://localhost:{PORT}/pde/")
        print(f"/pde: {DOCS_SITE}")
        httpd.serve_forever()
